name: CI/CD for React and Azure Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Use Node.js 16.x

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-

    - name: Install dependencies (frontend)
      run: |
        cd react-client
        npm install

    - name: Build frontend
      run: |
        cd react-client
        CI=false npm run build # Set CI=false to avoid treating warnings as errors

    - name: Install dependencies (backend)
      run: |
        cd function-api
        npm install

    - name: Build backend
      run: |
        cd function-api
        CI=false npm run build # Set CI=false to avoid treating warnings as errors

    - name: Azure Login with OpenID Connect
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: 'react-client/build'
        api_location: 'function-api/dist'
        output_location: 'react-client/build'
        app_build_command: 'npm run build'
        api_build_command: 'npm run build'
        skip_app_build: false
        skip_api_build: false    
      env: 
        REACT_APP_AZURE_APP_ID: 'a07be3cc-91fb-45d1-9564-77d2a9ac7be3'
        REACT_APP_AZURE_SERVER_APP_ID: 'a07be3cc-91fb-45d1-9564-77d2a9ac7be3'
        REACT_APP_SP_ROOT_SITE_URL: 'https://spefunction.azurewebsites.net'
        SPE_CONTAINER_TYPE_ID: 'b7487f5e-3aec-02fe-1b67-f45441a7d315'