name: Deploy SharePoint Container

on:
  workflow_dispatch:
  push:
    branches:
      - main    
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_sharepoint_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_SERVICEPRINCIPAL_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Uninstall legacy PnP PowerShell module
      run: |
        if (Get-Module -ListAvailable -Name SharePointPnPPowerShellOnline) {
          Uninstall-Module -Name SharePointPnPPowerShellOnline -AllVersions -Force
        }
      shell: pwsh
  
    - name: Install new PnP PowerShell module
      run: |
        Install-Module -Name PnP.PowerShell -Scope CurrentUser -Force
        # Validate installation
        Get-Module -Name PnP.PowerShell -ListAvailable
      shell: pwsh            


    - name: Run PowerShell Script to Create Container Type
      shell: pwsh
      run: |

        $siteUrl = 'https://pkssandbox-admin.sharepoint.com'
  
        # Connect to SharePoint Online
        Connect-PnPOnline -Url $siteUrl -DeviceLogin

        # Your PnP PowerShell commands
        Write-Host "Hello World"


        # Create container type
        New-PnPContainerType -TrialContainerType -ContainerTypeName $containerTypeName -OwningApplicationId $owningApplicationId

