name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SonarQube environment variables
      run: |
        echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV
        echo "SONAR_HOST_URL=https://sonar.provoke.co.nz" >> $GITHUB_ENV
        echo "SONAR_SCANNER_OPTS=-Dsonar.ssl.verifyServerCertificate=false" >> $GITHUB_ENV

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: -Dsonar.organization=provoke -Dsonar.sources=. -Dsonar.projectKey=ARLDigital
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
